import type { Order } from '../model/types';

export interface TableOrder {
  table: string;
  order: Order[];
}

export const mockOrders: TableOrder[] = [
  {
    table: '1',
    order: [
      {
        id: ' item-101',
        category: 'Appetizer',
        name: 'Roasted Tomato Basil Soup',
        imageAlt: 'Tomato Soup bowl',
        imageUrl: 'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=64&h=64&fit=crop',
        price: 6.99,
        amount: 1,
        comment: '',
      },
      {
        id: ' item-102',
        category: 'Main Course',
        name: 'Pan-Seared Atlantic Salmon',
        imageAlt: 'Seared Salmon fillet',
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=64&h=64&fit=crop',
        price: 22.5,
        amount: 1,
        comment: 'Dressing on the side',
      },
      {
        id: ' item-103',
        category: 'Drinks',
        name: 'Fresh Mint Lemonade',
        imageAlt: 'Glass of Lemonade',
        imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=64&h=64&fit=crop',
        price: 4.0,
        amount: 1,
        comment: 'Less ice',
      },
    ],
  },
  {
    table: '3',
    order: [
      {
        id: ' item-301',
        category: 'Appetizer',
        name: 'Caprese Salad',
        imageAlt: 'Caprese Salad',
        imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=64&h=64&fit=crop',
        price: 10.5,
        amount: 1,
        comment: 'Extra balsamic glaze',
      },
      {
        id: ' item-302',
        category: 'Main Course',
        name: 'Fettuccine Alfredo',
        imageAlt: 'Fettuccine Alfredo',
        imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=64&h=64&fit=crop',
        price: 17.99,
        amount: 1,
        comment: 'Add grilled shrimp',
      },
      {
        id: ' item-303',
        category: 'Drinks',
        name: 'House Cabernet Sauvignon',
        imageAlt: 'Red Wine Glass',
        imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=64&h=64&fit=crop',
        price: 9.0,
        amount: 2,
        comment: '',
      },
      {
        id: ' item-304',
        category: 'Dessert',
        name: 'Classic Tiramisu',
        imageAlt: 'Tiramisu slice',
        imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=64&h=64&fit=crop',
        price: 8.5,
        amount: 1,
        comment: 'Two spoons',
      },
    ],
  },

  {
    table: '6',
    order: [
      {
        id: 'item-601',
        category: 'Appetizer',
        name: 'Garlic Butter Breadsticks',
        imageAlt: 'Breadsticks',
        imageUrl: 'https://images.unsplash.com/photo-1625242662167-9ba73d268139?w=64&h=64&fit=crop',
        price: 6.25,
        amount: 1,
        comment: '',
      },
      {
        id: 'item-602',
        category: 'Main Course',
        name: 'Ribeye Steak with Mashed Potatoes',
        imageAlt: 'Ribeye Steak',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=64&h=64&fit=crop',
        price: 29.99,
        amount: 2,
        comment: 'Both Medium Rare',
      },
      {
        id: 'item-603',
        category: 'Drinks',
        name: 'Local IPA Craft Beer',
        imageAlt: 'Pint of Beer',
        imageUrl: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb13?w=64&h=64&fit=crop',
        price: 7.5,
        amount: 3,
        comment: '',
      },
      {
        id: 'item-604',
        category: 'Dessert',
        name: 'Chocolate Lava Cake',
        imageAlt: 'Lava Cake',
        imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=64&h=64&fit=crop',
        price: 8.99,
        amount: 1,
        comment: 'With vanilla ice cream',
      },
    ],
  },
  {
    table: '7',
    order: [
      {
        id: 'item-701',
        category: 'Appetizer',
        name: 'Bruschetta',
        imageAlt: 'Bruschetta',
        imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=64&h=64&fit=crop',
        price: 8.99,
        amount: 1,
        comment: '',
      },
      {
        id: 'item-702',
        category: 'Main Course',
        name: 'Grilled Chicken Caesar Salad',
        imageAlt: 'Grilled Chicken Caesar Salad',
        imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=64&h=64&fit=crop',
        price: 12.99,
        amount: 1,
        comment: '',
      },
      {
        id: 'item-703',
        category: 'Main Course',
        name: 'Classic Cheeseburger with Fries',
        imageAlt: 'Classic Cheeseburger',
        imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=64&h=64&fit=crop',
        price: 14.99,
        amount: 1,
        comment: 'Add 1 extra cheese',
      },
      {
        id: 'item-704',
        category: 'Drinks',
        name: 'Iced Tea',
        imageAlt: 'Iced Tea',
        imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=64&h=64&fit=crop',
        price: 2.99,
        amount: 2,
        comment: '',
      },
      {
        id: 'item-705',
        category: 'Dessert',
        name: 'New York Cheesecake',
        imageAlt: 'New York Cheesecake',
        imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=64&h=64&fit=crop',
        price: 6.99,
        amount: 1,
        comment: '',
      },
    ],
  },
];
